import React, { useState, useEffect } from 'react';
import { Proposal, SchedulingRun } from '../types/api';
import { api } from '../api/client';
import {
  CheckCircle2,
  XCircle,
  AlertTriangle,
  User,
  MapPin,
  RefreshCw,
  Info,
  Calendar,
} from 'lucide-react';

interface ProposalsPageProps {
  onSelectCase: (caseId: string) => void;
}

export const ProposalsPage: React.FC<ProposalsPageProps> = ({ onSelectCase }) => {
  const [run, setRun] = useState<SchedulingRun | null>(null);
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Rejection modal state
  const [rejectingProposalId, setRejectingProposalId] = useState<string | null>(null);
  const [rejectionReason, setRejectionReason] = useState<string>('');
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  // Per-proposal inline error tracking (e.g., 409 conflict messages)
  const [proposalErrors, setProposalErrors] = useState<Record<string, string>>({});
  const [successNotices, setSuccessNotices] = useState<Record<string, string>>({});

  const fetchProposals = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const latestRun = await api.getLatestSchedulingRun();
      setRun(latestRun);
      setProposals(latestRun.proposals || []);
    } catch (err: any) {
      if (err.status === 404) {
        setError('No completed scheduling run found. Run the scheduling engine from the Admin Batch page or wait for the nightly run.');
      } else {
        setError(err.message || 'Failed to load scheduling proposals');
      }
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchProposals();
  }, []);

  const handleApprove = async (proposalId: string) => {
    setProposalErrors((prev) => ({ ...prev, [proposalId]: '' }));
    setSuccessNotices((prev) => ({ ...prev, [proposalId]: '' }));
    setIsSubmitting(true);
    try {
      await api.approveProposal(proposalId);
      setSuccessNotices((prev) => ({
        ...prev,
        [proposalId]: 'Proposal approved and committed to official hearing calendar.',
      }));
      // Update local status to APPROVED
      setProposals((prev) =>
        prev.map((p) => (p.proposalId === proposalId ? { ...p, status: 'APPROVED' } : p))
      );
    } catch (err: any) {
      setProposalErrors((prev) => ({
        ...prev,
        [proposalId]: err.status === 409
          ? `Conflict (409): ${err.message}`
          : err.message || 'Approval failed',
      }));
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleOpenReject = (proposalId: string) => {
    setRejectingProposalId(proposalId);
    setRejectionReason('');
    setProposalErrors((prev) => ({ ...prev, [proposalId]: '' }));
  };

  const handleConfirmReject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!rejectingProposalId) return;

    if (!rejectionReason.trim()) {
      alert('A rejection reason is required for judicial registry logs.');
      return;
    }

    setIsSubmitting(true);
    try {
      await api.rejectProposal(rejectingProposalId, rejectionReason.trim());
      setSuccessNotices((prev) => ({
        ...prev,
        [rejectingProposalId]: `Proposal rejected: "${rejectionReason.trim()}"`,
      }));
      setProposals((prev) =>
        prev.map((p) =>
          p.proposalId === rejectingProposalId
            ? { ...p, status: 'REJECTED', rejectionReason: rejectionReason.trim() }
            : p
        )
      );
      setRejectingProposalId(null);
    } catch (err: any) {
      setProposalErrors((prev) => ({
        ...prev,
        [rejectingProposalId]: err.message || 'Rejection failed',
      }));
      setRejectingProposalId(null);
    } finally {
      setIsSubmitting(false);
    }
  };

  const statusBadge = (status: string) => {
    switch (status) {
      case 'PROPOSED':
        return 'bg-blue-50 text-blue-800 border-blue-200';
      case 'APPROVED':
        return 'bg-emerald-50 text-emerald-800 border-emerald-300';
      case 'REJECTED':
        return 'bg-red-50 text-red-800 border-red-300';
      case 'SUPERSEDED':
        return 'bg-slate-100 text-slate-600 border-slate-300';
      default:
        return 'bg-slate-50 text-slate-700 border-slate-200';
    }
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight">
            Proposed Hearing Allocations
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Latest optimization run generated by the weighted constraint-satisfaction engine. Review explainable rationale before approving.
          </p>
        </div>

        <button
          onClick={fetchProposals}
          disabled={isLoading}
          className="inline-flex items-center gap-1.5 px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-2xs self-start sm:self-auto"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh Proposals
        </button>
      </div>

      {/* Run Summary Banner */}
      {run && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-xs flex flex-wrap items-center justify-between gap-4 text-xs">
          <div className="flex items-center gap-4">
            <div>
              <span className="text-slate-400 text-[11px] block">Run Status</span>
              <span className="font-bold text-emerald-800 uppercase tracking-wide px-2 py-0.5 rounded bg-emerald-50 border border-emerald-200 inline-block mt-0.5">
                {run.status}
              </span>
            </div>
            <div>
              <span className="text-slate-400 text-[11px] block">Execution Time</span>
              <span className="font-medium text-slate-800 block mt-0.5">
                {new Date(run.triggeredAt).toLocaleString('en-IN', { timeZone: 'UTC' })}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-6">
            <div className="text-center">
              <span className="text-slate-400 text-[11px] block">Cases Input</span>
              <span className="text-sm font-bold text-slate-900">{run.totalCasesInput}</span>
            </div>
            <div className="text-center">
              <span className="text-slate-400 text-[11px] block">Allocated</span>
              <span className="text-sm font-bold text-blue-900">{run.totalAssigned}</span>
            </div>
            <div className="text-center">
              <span className="text-slate-400 text-[11px] block">Unschedulable</span>
              <span className="text-sm font-bold text-amber-700">{run.totalUnschedulable}</span>
            </div>
            <div className="text-center">
              <span className="text-slate-400 text-[11px] block">Horizon</span>
              <span className="text-sm font-bold text-slate-900">{run.horizonDays} days</span>
            </div>
          </div>
        </div>
      )}

      {/* Proposals List */}
      <div className="space-y-3">
        {isLoading ? (
          <div className="py-20 text-center text-slate-500 bg-white rounded-xl border border-slate-200 text-xs">
            <div className="w-6 h-6 border-2 border-blue-900 border-t-transparent rounded-full animate-spin mx-auto mb-2"></div>
            Loading latest scheduling proposals...
          </div>
        ) : error ? (
          <div className="p-8 text-center bg-white rounded-xl border border-slate-200 text-xs space-y-2">
            <Info className="w-6 h-6 text-slate-400 mx-auto" />
            <p className="text-slate-700 font-medium">{error}</p>
          </div>
        ) : proposals.length === 0 ? (
          <div className="p-12 text-center bg-white rounded-xl border border-slate-200 text-xs text-slate-400 italic">
            No proposals available in the latest run.
          </div>
        ) : (
          proposals.map((p) => {
            const hasError = !!proposalErrors[p.proposalId];
            const hasSuccess = !!successNotices[p.proposalId];
            const slotDate = new Date(p.slotStartTime);

            return (
              <div
                key={p.proposalId}
                className="bg-white rounded-xl border border-slate-200 shadow-xs hover:border-slate-300 transition-all p-5 space-y-3"
              >
                {/* Proposal Inline Alerts */}
                {hasError && (
                  <div className="p-3 bg-red-50 border border-red-200 rounded-lg flex items-start gap-2 text-red-800 text-xs animate-in fade-in">
                    <AlertTriangle className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
                    <div>
                      <p className="font-bold">Assignment Conflict</p>
                      <p className="mt-0.5 leading-relaxed">{proposalErrors[p.proposalId]}</p>
                    </div>
                  </div>
                )}

                {hasSuccess && (
                  <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-lg flex items-center gap-2 text-emerald-800 text-xs animate-in fade-in">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>{successNotices[p.proposalId]}</span>
                  </div>
                )}

                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100">
                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => onSelectCase(p.caseId)}
                      className="font-mono text-base font-bold text-blue-900 hover:underline flex items-center gap-1"
                    >
                      {p.caseNumber}
                    </button>
                    <span
                      className={`text-[10px] uppercase font-bold tracking-wider px-2.5 py-0.5 rounded-full border ${statusBadge(
                        p.status
                      )}`}
                    >
                      {p.status}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-500">Urgency Score:</span>
                    <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-blue-50 text-blue-900 border border-blue-200">
                      {p.scoreAtScheduling ? p.scoreAtScheduling.toFixed(1) : 'N/A'}
                    </span>
                  </div>
                </div>

                {/* Assignment specifics */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs bg-slate-50 p-3 rounded-lg border border-slate-200/80">
                  <div className="flex items-center gap-2 text-slate-800">
                    <User className="w-4 h-4 text-slate-400 shrink-0" />
                    <div>
                      <span className="text-[11px] text-slate-500 block">Judge</span>
                      <strong className="text-slate-900">{p.judgeName || 'Unassigned'}</strong>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-slate-800">
                    <MapPin className="w-4 h-4 text-slate-400 shrink-0" />
                    <div>
                      <span className="text-[11px] text-slate-500 block">Courtroom</span>
                      <strong className="text-slate-900">{p.courtroomName || 'Unassigned'}</strong>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-slate-800">
                    <Calendar className="w-4 h-4 text-slate-400 shrink-0" />
                    <div>
                      <span className="text-[11px] text-slate-500 block">Proposed Slot</span>
                      <strong className="text-indigo-950">
                        {slotDate.toLocaleString('en-IN', {
                          weekday: 'short',
                          day: 'numeric',
                          month: 'short',
                          hour: '2-digit',
                          minute: '2-digit',
                          timeZone: 'UTC',
                        })}{' '}
                        ({p.durationMinutes}m)
                      </strong>
                    </div>
                  </div>
                </div>

                {/* Explainable Decision Log */}
                {p.explanation && (
                  <div className="text-xs text-slate-600 bg-blue-50/40 p-2.5 rounded-lg border border-blue-100/60 leading-relaxed">
                    <span className="font-semibold text-blue-950">Optimization Explanation: </span>
                    {p.explanation}
                  </div>
                )}

                {/* Rejection reason if rejected */}
                {p.status === 'REJECTED' && p.rejectionReason && (
                  <div className="text-xs text-red-800 bg-red-50 p-2.5 rounded-lg border border-red-200">
                    <strong>Rejection Justification: </strong>
                    {p.rejectionReason}
                  </div>
                )}

                {/* Action buttons (only enabled if PROPOSED) */}
                {p.status === 'PROPOSED' && (
                  <div className="pt-2 flex justify-end gap-2">
                    <button
                      onClick={() => handleOpenReject(p.proposalId)}
                      disabled={isSubmitting}
                      className="px-3 py-1.5 border border-slate-300 rounded-md text-xs font-semibold text-slate-700 hover:bg-red-50 hover:text-red-700 hover:border-red-300 transition-colors flex items-center gap-1"
                    >
                      <XCircle className="w-3.5 h-3.5" />
                      Reject Proposal
                    </button>
                    <button
                      onClick={() => handleApprove(p.proposalId)}
                      disabled={isSubmitting}
                      className="px-3.5 py-1.5 bg-blue-900 text-white rounded-md text-xs font-semibold hover:bg-blue-800 transition-colors shadow-2xs flex items-center gap-1.5"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      Approve & Commit
                    </button>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Reject Modal */}
      {rejectingProposalId && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-md w-full border border-slate-200 overflow-hidden animate-in fade-in">
            <div className="bg-slate-900 px-6 py-4 text-white">
              <h3 className="text-base font-semibold">Reject Proposed Allocation</h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Record mandatory justification for the judicial audit log.
              </p>
            </div>
            <form onSubmit={handleConfirmReject} className="p-6 space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Reason for Rejection *
                </label>
                <textarea
                  required
                  rows={3}
                  value={rejectionReason}
                  onChange={(e) => setRejectionReason(e.target.value)}
                  placeholder="e.g. Counsel not available on date; Bench specialization mismatch; Witness attendance issue"
                  className="w-full text-xs rounded-md border border-slate-300 p-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setRejectingProposalId(null)}
                  disabled={isSubmitting}
                  className="px-3 py-1.5 border border-slate-300 rounded-md text-xs font-medium text-slate-700 hover:bg-slate-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-4 py-1.5 bg-red-600 text-white rounded-md text-xs font-semibold hover:bg-red-700 disabled:opacity-50"
                >
                  Confirm Rejection
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
